#!/bin/bash

export LUA_PATH="/usr/share/lua/5.1/?.lua;/usr/share/lua/5.1/?/init.lua;$LUA_PATH"
export LUA_CPATH="/usr/local/lib/lua/5.1/?.so;/usr/lib/x86_64-linux-gnu/lua/5.1/?.so;$LUA_CPATH"

export TERRA_PATH="./src/?.t"

busted --lua=terra --loaders=terra
